name: intro-ml
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.8.13
  - pip
  - pip:
      - albumentations
      - efficientnet_pytorch
      - jupyter
      - keras
      - lightgbm
      - matplotlib
      - numpy
      - pandas
      - pytorch_lightning
      - ray[tune]
      - scikit-image
      - scikit-learn
      - scipy
      - seaborn
      - tensorboard
      - tensorflow
      - torch
      - torchvision
      - tqdm
